workspace:
  base: /go
  path: src/github.com/yanzay/besto

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test

  publish:
    image: plugins/docker
    repo: yanzay/besto
    tags: [ latest ]
