workspace:
  base: /go
  path: src/github.com/yanzay/besto

pipeline:
  build:
    image: golang
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
      - go test

  publish:
    image: plugins/docker
    repo: yanzay/besto
    username: yanzay
    tags: [ latest ]
    secrets: [ DOCKER_PASSWORD ]

  deploy:
    image: appleboy/drone-ssh
    host: 67.207.72.170
    port: 22
    script:
      - cd infra
      - docker-compose pull besto
      - docker-compose up -d
    when:
      status: success
    secrets: [ SSH_KEY ]

  telegram:
    image: appleboy/drone-telegram
    to: 93068777
    when:
      status: [ success, failure ]
    secrets:
      - source: NOTIFICATION_TOKEN
        target: PLUGIN_TOKEN
