workspace:
  base: /go
  path: src/github.com/yanzay/besto

pipeline:
  build:
    image: golang
    commands:
      - go build
      - go test

  publish:
    image: plugins/docker
    repo: yanzay/besto
    username: yanzay
    tags: [ latest ]
    secrets: [ DOCKER_PASSWORD ]

  telegram:
    image: appleboy/drone-telegram
    token: ${TELEGRAM_DRONE_TOKEN}
    to: 93068777
    when:
      status: [ success, failure ]

